//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Linq_Project
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductStore
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ProductStore()
        {
            this.ClientPermissionDetails = new HashSet<ClientPermissionDetail>();
            this.SupplyPermissionDetails = new HashSet<SupplyPermissionDetail>();
        }
    
        public int Product_ID { get; set; }
        public string Store_Name { get; set; }
        public System.DateTime Product_Date { get; set; }
        public Nullable<int> Quantity { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ClientPermissionDetail> ClientPermissionDetails { get; set; }
        public virtual Product Product { get; set; }
        public virtual Store Store { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SupplyPermissionDetail> SupplyPermissionDetails { get; set; }
    }
}
