//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Linq_Project
{
    using System;
    using System.Collections.Generic;
    
    public partial class SupplyPermissionDetail
    {
        public int Product_ID { get; set; }
        public int ID { get; set; }
        public string Store_Name { get; set; }
        public string Quantity { get; set; }
        public System.DateTime Product_Date { get; set; }
    
        public virtual Product Product { get; set; }
        public virtual ProductStore ProductStore { get; set; }
        public virtual Store Store { get; set; }
        public virtual SupplyPermission SupplyPermission { get; set; }
    }
}
