//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Linq_Project
{
    using System;
    using System.Collections.Generic;
    
    public partial class Supplier
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Supplier()
        {
            this.SupplyPermissions = new HashSet<SupplyPermission>();
        }
    
        public int Suppliers_ID { get; set; }
        public string Suppliers_Name { get; set; }
        public Nullable<int> Suppliers_Phone { get; set; }
        public string Suppliers_fax { get; set; }
        public Nullable<int> Suppliers_Mobile { get; set; }
        public string Suppliers_Email { get; set; }
        public string Suppliers_Website { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SupplyPermission> SupplyPermissions { get; set; }
    }
}
